import type { Lang } from "@/lib/i18n/strings";

export function meetupCopy(lang: Lang) {
  const zh = lang === "zh";
  return {
    slogan: zh ? "尋找對的人，不論是 1 對 1 還是群組活動" : "Find the right people, one to one or in a group",
    footerMark: zh ? "尋找對的人" : "Find the right people",
    lead: zh ? "看看最新的人和活動，覺得合適再自己申請。" : "See the latest people and activities, then apply if it feels right.",
    oneToOne: zh ? "1 對 1" : "1 to 1",
    groups: zh ? "群組活動" : "Group activities",
    oneToOneHint: zh ? "認識一個人，由你決定要不要繼續" : "Meet one person. You decide whether to continue.",
    groupsHint: zh ? "發起或加入一場活動" : "Host or join an activity",
    latest: zh ? "最新" : "Latest",
    searchPlaceholder: zh ? "用一句話描述你想找的人或活動" : "Describe the person or activity you want",
    searchLabel: zh ? "AI 搜尋" : "AI search",
    searchHint: zh ? "由 AI 理解你的描述，搜尋公開的人和活動" : "AI reads your words and searches public people and activities",
    login: zh ? "登入" : "Log in",
    register: zh ? "註冊" : "Register",
    publish: zh ? "發布" : "Publish",
    apply: zh ? "查看並申請" : "View and apply",
    yours: zh ? "你的發布" : "Your post",
    empty: zh ? "這裡還沒有公開的卡片。發布一則，讓對的人找到你。" : "No public cards yet. Publish one so the right people can find you.",
    emptyFiltered: zh ? "沒有符合的卡片。試試其他關鍵字。" : "Nothing matches. Try another search.",
    emptySection: zh ? "這個分類還沒有卡片。" : "Nothing in this category yet.",
    guestMore: zh ? "登入後可以看到更多" : "Log in to see more",
    storyTitle: zh ? "人找人的地方。興趣，可以變成一起出現。" : "A place to find people. Shared interests turn into plans.",
    storyLead: zh
      ? "不論是認識一個人，還是參加一場活動，先看看公開的帖，覺得合適再自己申請。"
      : "Meet one person, or join an activity. Look through public posts, then apply when it feels right.",
    storyJoin: zh ? "加入 Vennode" : "Join Vennode",
    joinTitle: zh ? "一起開始" : "Start together",
    joinLead: zh ? "註冊免費。你可以發布 1 對 1，也可以發起群組活動。" : "Signing up is free. Publish a 1 to 1 post, or host a group activity.",
    joinCta: zh ? "免費註冊" : "Sign up free",
    categoriesTitle: zh ? "從這些方向看看" : "Start from a direction",
    howTitle: zh ? "Vennode 怎麼用" : "How Vennode works",
    how1Title: zh ? "看看公開的人和活動" : "See public people and activities",
    how1Body: zh ? "先瀏覽 1 對 1 和群組活動，找到你有興趣的帖。" : "Browse 1 to 1 posts and group activities, and open the ones that interest you.",
    how1Link: zh ? "開始看看" : "Start looking",
    how2Title: zh ? "找到你想認識的人" : "Find someone who fits",
    how2Body: zh ? "覺得合適就自己申請。對方同意之後，才會開啟聯絡。" : "Apply yourself when it feels right. Contact opens after they approve.",
    how2Link: zh ? "去探索廣場" : "Go to Explore",
    how3Title: zh ? "發布你自己的帖" : "Publish your own post",
    how3Body: zh ? "寫下 1 對 1，或發起一場群組活動，讓對的人找到你。" : "Write a 1 to 1 post, or host a group activity, so the right people can find you.",
    how3Link: zh ? "開始發布" : "Start a post",
    catLove: zh ? "附近的人" : "Near you",
    catClass: zh ? "一場活動" : "An activity",
    catClub: zh ? "一起做的事" : "Something shared",
    catWeekly: zh ? "約好時間" : "A set time",
    catOutdoor: zh ? "戶外與旅行" : "Outdoors and travel",
    catSocial: zh ? "認識新朋友" : "Meeting people",
    catHobby: zh ? "興趣與嗜好" : "Hobbies",
    catSport: zh ? "運動" : "Sports",
    catWork: zh ? "一起做事" : "Building together",
    portal: zh ? "我的" : "Mine",
    settings: zh ? "設定" : "Settings",
    messages: zh ? "訊息" : "Messages",
    explore: zh ? "探索" : "Explore",
    advanced: zh ? "進階管理" : "Advanced",
    signOut: zh ? "登出" : "Sign out",
    menu: zh ? "選單" : "Menu",
    stepType: zh ? "類型" : "Type",
    stepDetails: zh ? "內容" : "Details",
    stepPreview: zh ? "預覽" : "Preview",
    next: zh ? "下一步" : "Next",
    back: zh ? "返回" : "Back",
    title: zh ? "標題" : "Title",
    titleHint: zh ? "最多 20 個中文字，或 40 個英文字" : "Up to 20 Chinese characters, or 40 English letters",
    cover: zh ? "封面" : "Cover",
    coverHint: zh ? "選一張照片。沒有的話會用一張預設圖。" : "Choose a photo. Without one, a default image is used.",
    coverAdd: zh ? "上傳封面" : "Upload a cover",
    coverChange: zh ? "更換封面" : "Change cover",
    coverRemove: zh ? "移除" : "Remove",
    coverType: zh ? "請上傳 JPG、PNG 或 WebP。" : "Upload a JPG, PNG, or WebP image.",
    coverSize: zh ? "圖片需小於 5MB。" : "Image must be under 5MB.",
    coverFailed: zh ? "封面上傳失敗，請再試一次。" : "The cover could not be uploaded. Try again.",
    details: zh ? "詳情" : "Details",
    place: zh ? "地點" : "Location",
    when: zh ? "日期與時間" : "Date and time",
    who: zh ? "期望" : "Expectations",
    hashtags: zh ? "標籤" : "Hashtags",
    hashtagsHint: zh ? "用逗號或空白分開，例如 羽毛球, 教練" : "Separate with commas or spaces, for example badminton, coach",
    aiPolish: zh ? "✨ 使用 AI 潤色內容" : "✨ Polish with AI",
    polishing: zh ? "潤色中…" : "Polishing…",
    polishFailed: zh ? "潤色沒有完成，請再試一次。" : "Polishing didn't finish. Try again.",
    polishShort: zh ? "先寫多一點詳情，AI 才有內容可以潤色。" : "Write a bit more detail before polishing.",
    previewLead: zh ? "確認一次，沒問題就發布。" : "Check everything, then publish.",
    publishNow: zh ? "發布" : "Publish",
    saving: zh ? "發布中…" : "Publishing…",
    needTitle: zh ? "請寫一個標題" : "Add a title",
    needPlace: zh ? "請寫地點或線上" : "Add a place or say it's online",
    needWhen: zh ? "群組活動需要時間" : "Group activities need a time",
    needWho: zh ? "請寫你的期望" : "Add what you expect",
    needBody: zh ? "詳情至少需要 12 個字" : "Details need at least 12 characters",
    needTitleLength: zh ? "標題請保持在 20 個中文字以內" : "Keep the title within 20 Chinese characters",
    editTitle: zh ? "編輯發布" : "Edit post",
    createTitle: zh ? "發布" : "Publish",
    hosted: zh ? "我發布的" : "Your posts",
    seePeople: zh ? "想看其他人的 1 對 1？公開的帖都在探索廣場。" : "Want to see other 1 to 1 posts? They're on Explore.",
    seeGroups: zh ? "想看其他人的群組活動？公開的活動都在探索廣場。" : "Want to see other group activities? They're on Explore.",
    visitSquare: zh ? "去探索廣場" : "Go to Explore",
    incoming: zh ? "收到的申請" : "Applications",
    suggestions: zh ? "AI 建議" : "AI suggestions",
    suggestHint: zh ? "依這則發布，建議你可以邀請的人。對方會看到這則內容。" : "People who fit this post. They'll see this post in the invite.",
    suggestEmpty: zh ? "還沒有建議。按一下，讓 AI 依這則發布找人。" : "No suggestions yet. Ask AI to look for people who fit this post.",
    suggestNone: zh ? "AI 已經幫你找過，暫時沒有合適的人。" : "AI already looked. Nobody fits this post right now.",
    suggestHold: zh ? "請稍後再試" : "Try again later",
    suggestLoad: zh ? "幫我找適合的人" : "Find people for this post",
    suggesting: zh ? "尋找中…" : "Looking…",
    invite: zh ? "邀請" : "Invite",
    applicationCount: zh ? "則申請" : "applications",
    approve: zh ? "同意" : "Approve",
    decline: zh ? "婉拒" : "Decline",
    pending: zh ? "等待回覆" : "Waiting",
    approved: zh ? "已同意" : "Approved",
    rejected: zh ? "已婉拒" : "Declined",
    openChat: zh ? "開啟對話" : "Open chat",
    locked: zh ? "同意之後才會開啟聯絡" : "Contact unlocks after you approve",
    closePost: zh ? "結束" : "Close",
    reopen: zh ? "重新開放" : "Reopen",
    noPosts: zh ? "你還沒有這類發布。" : "You don't have this kind of post yet.",
    noIncoming: zh ? "還沒有人申請。" : "No requests yet.",
    noOutgoing: zh ? "你還沒有送出申請。" : "You haven't applied yet.",
    settingsLead: zh ? "暱稱、城市、興趣與帳戶。" : "Nickname, city, interests, and account.",
    nickname: zh ? "暱稱" : "Nickname",
    city: zh ? "城市" : "City",
    interests: zh ? "興趣" : "Interests",
    save: zh ? "儲存" : "Save",
    saved: zh ? "已儲存" : "Saved",
    fullProfile: zh ? "編輯完整檔案" : "Edit full profile",
    account: zh ? "帳戶" : "Account",
    age: zh ? "年齡帶" : "Age band",
    gender: zh ? "性別（可選）" : "Gender (optional)",
    bio: zh ? "自我介紹" : "About you",
    industry: zh ? "領域" : "Field",
    superpower: zh ? "你能提供的" : "What you offer",
    languages: zh ? "語言" : "Languages",
    tagsHint: zh ? "至少點三個興趣，或自己輸入後按 Enter。" : "Pick at least three interests, or type your own and press Enter.",
    needTags: zh ? "請至少選擇 3 個興趣" : "Choose at least 3 interests",
    online: zh ? "線上" : "Online",
    where: zh ? "地點" : "Place",
  };
}

export const INTEREST_SUGGESTIONS = ["科技", "戶外", "創業", "語言交換", "設計", "音樂", "閱讀", "美食", "運動", "旅行"];
