import type { Lang } from "@/lib/i18n/strings";

export function meetupCopy(lang: Lang) {
  const zh = lang === "zh";
  return {
    slogan: zh ? "遇見對的人，開啟靈感與連結" : "Find the right people, one to one or in a group",
    footerMark: zh ? "遇見對的人" : "Find the right people",
    lead: zh ? "不論是一對一咖啡交流，還是有趣的群組活動，在這裡輕鬆展開真實對話。" : "See the latest people and activities, then apply if it feels right.",
    oneToOne: zh ? "1 對 1 交流" : "1 to 1",
    badgeOne: zh ? "1 對 1" : "1 to 1",
    groups: zh ? "群組活動" : "Group activities",
    typeOneDesc: zh ? "尋找一位特定領域的夥伴，進行深度對話或合作。" : "Find one person in a specific field for a real conversation or a collaboration.",
    typeGroupDesc: zh ? "發起多人群聚聚會、工作坊或週末戶外活動。" : "Host a meetup, workshop, or weekend outing for several people.",
    oneToOneHint: zh ? "尋找志同道合的夥伴，一對一探討事業、興趣或生活經驗。" : "Meet one person. You decide whether to continue.",
    groupsHint: zh ? "拓展社交圈，與一群有趣的人共度精彩週末。" : "Host or join an activity",
    latest: zh ? "最新" : "Latest",
    searchPlaceholder: zh ? "想找人聊創業、約打羽毛球，還是參加週末聚會？" : "Describe the person or activity you want",
    searchLabel: zh ? "AI 搜尋" : "AI search",
    searchHint: zh ? "✨ 用自然語言隨心描述，AI 幫你精準尋找公開需求與活動" : "AI reads your words and searches public people and activities",
    login: zh ? "登入" : "Log in",
    register: zh ? "免費註冊" : "Register",
    publish: zh ? "發布需求" : "Publish",
    apply: zh ? "查看詳情" : "View and apply",
    yours: zh ? "我的發布" : "Your post",
    empty: zh ? "目前還沒有公開的需求喔。發布一則，讓對的人找到你。" : "No public cards yet. Publish one so the right people can find you.",
    emptyFiltered: zh ? "這裡還沒有對上的內容，換個說法再試試？" : "Nothing matches. Try another search.",
    emptySection: zh ? "這個分類還沒有內容。" : "Nothing in this category yet.",
    guestMore: zh ? "登入後可以看到更多" : "Log in to see more",
    viewAll: zh ? "查看全部" : "See all",
    sendInvite: zh ? "發送連繫邀請" : "Send an invite",
    joinGroup: zh ? "報名參加活動" : "Join this activity",
    applyNow: zh ? "立即發送邀請" : "Send an invite",
    alreadyApplied: zh ? "已發送邀請" : "Invite sent",
    backToExplore: zh ? "返回探索廣場" : "Back to Explore",
    aboutEvent: zh ? "關於此活動 / 交流內容" : "About this",
    targetAudience: zh ? "期待認識的對象" : "Who they're hoping to meet",
    hostedBy: zh ? "發起人" : "Hosted by",
    detailWhen: zh ? "活動時間" : "When",
    detailPlace: zh ? "地點與形式" : "Where",
    stickyTitle: zh ? "準備好建立連結了嗎？" : "Ready to connect?",
    stickySub: zh ? "發送邀請後，對方同意即可解鎖聯絡方式並開始對話。" : "After they accept, you can start the conversation.",
    storyTitle: zh ? "遇見對的人，興趣也能變成一場約" : "A place to find people. Shared interests turn into plans.",
    storyLead: zh
      ? "先看看公開的交流和活動。覺得對味，再自己送出邀請。"
      : "Meet one person, or join an activity. Look through public posts, then apply when it feels right.",
    storyJoin: zh ? "免費註冊" : "Join Vennode",
    joinTitle: zh ? "一起開始" : "Start together",
    joinLead: zh ? "註冊免費。你可以發布 1 對 1 交流，也可以發起一場群組活動。" : "Signing up is free. Publish a 1 to 1 post, or host a group activity.",
    joinCta: zh ? "免費註冊" : "Sign up free",
    categoriesTitle: zh ? "從這些方向看看" : "Start from a direction",
    howTitle: zh ? "Vennode 怎麼用" : "How Vennode works",
    how1Title: zh ? "先看看大家在找什麼" : "See public people and activities",
    how1Body: zh ? "瀏覽 1 對 1 交流和群組活動，打開你有興趣的那一則。" : "Browse 1 to 1 posts and group activities, and open the ones that interest you.",
    how1Link: zh ? "開始看看" : "Start looking",
    how2Title: zh ? "遇到想認識的人，就打聲招呼" : "Find someone who fits",
    how2Body: zh ? "覺得合適就送出邀請。對方同意之後，才會開始對話。" : "Apply yourself when it feels right. Contact opens after they approve.",
    how2Link: zh ? "去探索廣場" : "Go to Explore",
    how3Title: zh ? "也發布你自己的需求" : "Publish your own post",
    how3Body: zh ? "寫下一對一交流，或發起一場群組活動，讓對的人找到你。" : "Write a 1 to 1 post, or host a group activity, so the right people can find you.",
    how3Link: zh ? "發布需求" : "Start a post",
    catLove: zh ? "附近的人" : "Near you",
    catClass: zh ? "一場活動" : "An activity",
    catClub: zh ? "一起做的事" : "Something shared",
    catWeekly: zh ? "約好時間" : "A set time",
    catOutdoor: zh ? "戶外與旅行" : "Outdoors and travel",
    catSocial: zh ? "認識新朋友" : "Meeting people",
    catHobby: zh ? "興趣與嗜好" : "Hobbies",
    catSport: zh ? "運動" : "Sports",
    catWork: zh ? "一起做事" : "Building together",
    portal: zh ? "我的" : "Mine",
    settings: zh ? "個人設定" : "Settings",
    messages: zh ? "訊息對話" : "Messages",
    explore: zh ? "探索廣場" : "Explore",
    advanced: zh ? "進階管理" : "Advanced",
    signOut: zh ? "登出" : "Sign out",
    menu: zh ? "選單" : "Menu",
    stepType: zh ? "選擇類型" : "Type",
    stepDetails: zh ? "填寫內容" : "Details",
    stepPreview: zh ? "預覽確認" : "Preview",
    next: zh ? "下一步" : "Next",
    back: zh ? "返回" : "Back",
    title: zh ? "標題" : "Title",
    titleHint: zh ? "最多 20 個中文字，或 40 個英文字" : "Up to 20 Chinese characters, or 40 English letters",
    cover: zh ? "封面" : "Cover",
    coverHint: zh ? "選一張照片。沒有的話會用一張預設圖。" : "Choose a photo. Without one, a default image is used.",
    coverAdd: zh ? "上傳封面" : "Upload a cover",
    coverChange: zh ? "更換封面" : "Change cover",
    coverRemove: zh ? "移除" : "Remove",
    coverType: zh ? "請上傳 JPG、PNG 或 WebP。" : "Upload a JPG, PNG, or WebP image.",
    coverSize: zh ? "圖片需小於 5MB。" : "Image must be under 5MB.",
    coverFailed: zh ? "封面上傳失敗，請再試一次。" : "The cover could not be uploaded. Try again.",
    showProfile: zh ? "公開我的個人檔案" : "Show my profile",
    showProfileRecommend: zh ? "建議" : "Recommended",
    showProfileHint: zh
      ? "別人可以看到你的名字和頭像，比較容易決定要不要認識你。取消勾選就會以匿名顯示。性別仍會公開。"
      : "People can see your name and photo, which makes it easier to decide to connect. Uncheck to stay anonymous. Gender stays visible.",
    profilePublic: zh ? "公開個人檔案" : "Public profile",
    profileAnonymous: zh ? "匿名顯示" : "Shown anonymously",
    details: zh ? "詳情" : "Details",
    place: zh ? "地點" : "Location",
    price: zh ? "金額" : "Price",
    priceNone: zh ? "不涉及金額" : "No money involved",
    pricePay: zh ? "申請人需要付款" : "Applicants need to pay",
    priceReceive: zh ? "申請人可以收到" : "Applicants can receive",
    priceAmount: zh ? "金額" : "Amount",
    priceCurrency: zh ? "貨幣" : "Currency",
    priceHint: zh ? "款項由雙方線下自行結算，Vennode 不經手付款，也不負責追討或退款。" : "People settle this offline. Vennode does not take, chase, or refund the money.",
    priceNeedAmount: zh ? "請填一個大於 0 的金額" : "Enter an amount greater than 0",
    when: zh ? "日期與時間" : "Date and time",
    who: zh ? "期望" : "Expectations",
    hashtags: zh ? "標籤" : "Hashtags",
    hashtagsHint: zh ? "用逗號或空白分開，例如 羽毛球, 教練" : "Separate with commas or spaces, for example badminton, coach",
    aiPolish: zh ? "✨ AI 幫我把描述寫得更吸引人" : "✨ Polish with AI",
    polishing: zh ? "潤色中…" : "Polishing…",
    polishFailed: zh ? "潤色沒有完成，請再試一次。" : "Polishing didn't finish. Try again.",
    polishShort: zh ? "先寫多一點詳情，AI 才有內容可以潤色。" : "Write a bit more detail before polishing.",
    previewLead: zh ? "再看一次，沒問題就發布。" : "Check everything, then publish.",
    publishNow: zh ? "確認發布" : "Publish",
    saving: zh ? "發布中…" : "Publishing…",
    needTitle: zh ? "請寫一個標題" : "Add a title",
    needPlace: zh ? "請寫地點或線上" : "Add a place or say it's online",
    needWhen: zh ? "群組活動需要時間" : "Group activities need a time",
    needWho: zh ? "請寫你的期望" : "Add what you expect",
    needBody: zh ? "詳情至少需要 12 個字" : "Details need at least 12 characters",
    needTitleLength: zh ? "標題請保持在 20 個中文字以內" : "Keep the title within 20 Chinese characters",
    editTitle: zh ? "編輯發布" : "Edit post",
    createTitle: zh ? "建立新發布" : "Publish",
    hosted: zh ? "我發布的需求" : "Your posts",
    seePeople: zh ? "想看其他人的 1 對 1 交流？公開的都在探索廣場。" : "Want to see other 1 to 1 posts? They're on Explore.",
    seeGroups: zh ? "想看其他人的群組活動？公開的活動都在探索廣場。" : "Want to see other group activities? They're on Explore.",
    visitSquare: zh ? "去探索廣場" : "Go to Explore",
    incoming: zh ? "收到的連繫申請" : "Applications",
    suggestions: zh ? "AI 建議" : "AI suggestions",
    suggestHint: zh ? "依這則需求，建議你可以邀請的人。對方會看到這則內容。" : "People who fit this post. They'll see this post in the invite.",
    suggestEmpty: zh ? "還沒有建議。按一下，讓 AI 依這則需求找人。" : "No suggestions yet. Ask AI to look for people who fit this post.",
    suggestNone: zh ? "AI 已經幫你找過，暫時還沒有特別合適的人。" : "AI already looked. Nobody fits this post right now.",
    suggestHold: zh ? "請稍後再試" : "Try again later",
    suggestLoad: zh ? "幫我找合適的人" : "Find people for this post",
    suggesting: zh ? "尋找中…" : "Looking…",
    invite: zh ? "邀請" : "Invite",
    applicationCount: zh ? "則申請" : "applications",
    approve: zh ? "同意連繫" : "Approve",
    decline: zh ? "婉拒" : "Decline",
    pending: zh ? "等待對方回應中" : "Waiting",
    approved: zh ? "已同意" : "Approved",
    rejected: zh ? "已婉拒" : "Declined",
    openChat: zh ? "開啟私訊對話" : "Open chat",
    locked: zh ? "對方同意後，才會開始對話" : "Contact unlocks after you approve",
    closePost: zh ? "結束" : "Close",
    reopen: zh ? "重新開放" : "Reopen",
    noPosts: zh ? "目前還沒有發布任何需求喔。點右上角「發布需求」，開始第一個連結吧。" : "You don't have this kind of post yet.",
    noIncoming: zh ? "暫無相關申請。" : "No requests yet.",
    noOutgoing: zh ? "你還沒有送出申請。" : "You haven't applied yet.",
    settingsLead: zh ? "暱稱、城市、興趣與帳戶。" : "Nickname, city, interests, and account.",
    nickname: zh ? "暱稱" : "Nickname",
    city: zh ? "城市" : "City",
    interests: zh ? "興趣" : "Interests",
    save: zh ? "儲存" : "Save",
    saved: zh ? "已儲存" : "Saved",
    fullProfile: zh ? "編輯完整檔案" : "Edit full profile",
    account: zh ? "帳戶" : "Account",
    age: zh ? "年齡帶" : "Age band",
    gender: zh ? "性別" : "Gender",
    genderHint: zh ? "必填。會顯示在每一則發布上，就算選擇匿名也一樣。" : "Required. Shown on every post, including anonymous ones.",
    needGender: zh ? "請選擇性別" : "Choose a gender",
    relatedTitle: zh ? "其他也可以看看" : "More to look at",
    bio: zh ? "自我介紹" : "About you",
    industry: zh ? "領域" : "Field",
    superpower: zh ? "你能提供的" : "What you offer",
    languages: zh ? "語言" : "Languages",
    tagsHint: zh ? "至少點三個興趣，或自己輸入後按 Enter。" : "Pick at least three interests, or type your own and press Enter.",
    needTags: zh ? "請至少選擇 3 個興趣" : "Choose at least 3 interests",
    online: zh ? "線上" : "Online",
    where: zh ? "地點" : "Place",
  };
}

export const INTEREST_SUGGESTIONS = ["科技", "戶外", "創業", "語言交換", "設計", "音樂", "閱讀", "美食", "運動", "旅行"];
