import type { Lang } from "@/lib/i18n/strings";

export function meetupCopy(lang: Lang) {
  const zh = lang === "zh";
  return {
    slogan: zh ? "尋找對的人，不論是 1 對 1 還是群組活動" : "Find the right people, one to one or in a group",
    oneToOne: zh ? "1 對 1" : "1 to 1",
    groups: zh ? "群組活動" : "Group activities",
    oneToOneHint: zh ? "認識一個人，由你決定要不要繼續" : "Meet one person. You decide whether to continue.",
    groupsHint: zh ? "發起或加入一場活動" : "Host or join an activity",
    latest: zh ? "最新" : "Latest",
    searchPlaceholder: zh ? "搜尋人、興趣或地點" : "Search people, interests, or places",
    searchLabel: zh ? "搜尋" : "Search",
    login: zh ? "登入" : "Log in",
    register: zh ? "註冊" : "Register",
    publish: zh ? "發布" : "Publish",
    apply: zh ? "查看並申請" : "View and apply",
    yours: zh ? "你的發布" : "Your post",
    empty: zh ? "這裡還沒有公開的卡片。發布一則，讓對的人找到你。" : "No public cards yet. Publish one so the right people can find you.",
    emptyFiltered: zh ? "沒有符合的卡片。試試其他關鍵字。" : "Nothing matches. Try another search.",
    guestMore: zh ? "登入後可以看到更多" : "Log in to see more",
    portal: zh ? "我的" : "Mine",
    settings: zh ? "設定" : "Settings",
    messages: zh ? "訊息" : "Messages",
    explore: zh ? "探索" : "Explore",
    advanced: zh ? "進階管理" : "Advanced",
    signOut: zh ? "登出" : "Sign out",
    menu: zh ? "選單" : "Menu",
    stepType: zh ? "類型" : "Type",
    stepDetails: zh ? "內容" : "Details",
    stepPreview: zh ? "預覽" : "Preview",
    next: zh ? "下一步" : "Next",
    back: zh ? "返回" : "Back",
    title: zh ? "標題" : "Title",
    place: zh ? "地點或線上" : "Place or online",
    when: zh ? "時間" : "Time",
    who: zh ? "你想找的人" : "Who you want to meet",
    aiDraft: zh ? "✨ 使用 AI 幫我生成描述" : "✨ Draft this with AI",
    aiPolish: zh ? "✨ 使用 AI 潤色內容" : "✨ Polish with AI",
    aiNote: zh ? "只幫你寫文字，不會自動配對任何人。" : "Writes the wording only. It never matches people for you.",
    publishNow: zh ? "發布" : "Publish",
    saving: zh ? "發布中…" : "Publishing…",
    needTitle: zh ? "請寫一個標題" : "Add a title",
    needPlace: zh ? "請寫地點或線上" : "Add a place or say it's online",
    needWhen: zh ? "群組活動需要時間" : "Group activities need a time",
    needWho: zh ? "請寫你想找的人" : "Say who you want to meet",
    editTitle: zh ? "編輯發布" : "Edit post",
    createTitle: zh ? "發布" : "Publish",
    hosted: zh ? "我發布的" : "Hosting",
    incoming: zh ? "收到的申請" : "Incoming requests",
    outgoing: zh ? "我送出的申請" : "Applications I sent",
    approve: zh ? "同意" : "Approve",
    decline: zh ? "婉拒" : "Decline",
    pending: zh ? "等待回覆" : "Waiting",
    approved: zh ? "已同意" : "Approved",
    rejected: zh ? "已婉拒" : "Declined",
    openChat: zh ? "開啟對話" : "Open chat",
    locked: zh ? "同意之後才會開啟聯絡" : "Contact unlocks after you approve",
    closePost: zh ? "結束" : "Close",
    reopen: zh ? "重新開放" : "Reopen",
    noPosts: zh ? "你還沒有這類發布。" : "You don't have this kind of post yet.",
    noIncoming: zh ? "還沒有人申請。" : "No requests yet.",
    noOutgoing: zh ? "你還沒有送出申請。" : "You haven't applied yet.",
    settingsLead: zh ? "暱稱、城市、興趣與帳戶。" : "Nickname, city, interests, and account.",
    nickname: zh ? "暱稱" : "Nickname",
    city: zh ? "城市" : "City",
    interests: zh ? "興趣" : "Interests",
    save: zh ? "儲存" : "Save",
    saved: zh ? "已儲存" : "Saved",
    fullProfile: zh ? "編輯完整檔案" : "Edit full profile",
    account: zh ? "帳戶" : "Account",
    age: zh ? "年齡帶" : "Age band",
    gender: zh ? "性別（可選）" : "Gender (optional)",
    bio: zh ? "自我介紹" : "About you",
    industry: zh ? "領域" : "Field",
    superpower: zh ? "你能提供的" : "What you offer",
    languages: zh ? "語言" : "Languages",
    tagsHint: zh ? "至少點三個興趣，或自己輸入後按 Enter。" : "Pick at least three interests, or type your own and press Enter.",
    needTags: zh ? "請至少選擇 3 個興趣" : "Choose at least 3 interests",
    online: zh ? "線上" : "Online",
    where: zh ? "地點" : "Place",
  };
}

export const INTEREST_SUGGESTIONS = ["科技", "戶外", "創業", "語言交換", "設計", "音樂", "閱讀", "美食", "運動", "旅行"];
